spring.data.mongodb.uri=mongodb+srv://thanh99902_db_user:17UgHAMV9rFqk5vc@cluster0.h8ajqhd.mongodb.net/YOUR_DB_NAME?retryWrites=true&w=majority
spring.data.mongodb.database=YOUR_DB_NAME
server.port=8080

# JWT config
app.jwt.secret=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=
app.jwt.expiration-ms=86400000